export const nursingAreas = [
  {
    title: "Medical-Surgical Nursing",
    icon: "medical",
    status: "progress",
    progress: 67,
    completed: 211,
    total: 316,
    date: "Last studied today",
    iconBg: "#D5EFE6",
  },
  {
    title: "Fundamentals Of Nursing",
    icon: "fundamentals",
    status: "complete",
    progress: 100,
    completed: 49,
    total: 49,
    date: "Finished Apr 28",
    iconBg: "#EEEEEE",
  },
  {
    title: "Maternal-Newborn Nursing",
    icon: "maternal",
    status: "progress",
    progress: 55,
    completed: 27,
    total: 49,
    date: "Last studied 3d ago",
    iconBg: "#FCE1EE",
  },
  {
    title: "Pharmacology",
    icon: "pharma",
    status: "progress",
    progress: 38,
    completed: 19,
    total: 49,
    date: "Last studied today",
    iconBg: "#F5E7C8",
  },
  {
    title: "Mental Health Nursing",
    icon: "mental",
    status: "progress",
    progress: 31,
    completed: 15,
    total: 49,
    date: "Last studied 1d ago",
    iconBg: "#E6D9FF",
  },
  {
    title: "Health Assessment",
    icon: "assessment",
    status: "complete",
    progress: 100,
    completed: 49,
    total: 49,
    date: "Finished Apr 22",
    iconBg: "#D5EFE6",
  },
  {
    title: "Community & Public Health",
    icon: "community",
    status: "notStarted",
    progress: 0,
    completed: 0,
    total: 49,
    date: "Begin reading",
    iconBg: "#FFE0EE",
  },
  {
    title: "Leadership & Management",
    icon: "leadership",
    status: "notStarted",
    progress: 0,
    completed: 0,
    total: 49,
    date: "Begin reading",
    iconBg: "#F7E7BF",
  },
  {
    title: "Legal & Ethical Nursing",
    icon: "legal",
    status: "notStarted",
    progress: 0,
    completed: 0,
    total: 49,
    date: "Begin reading",
    iconBg: "#EEEEEE",
  },
];